//// <auto-generated />
//using System;
//using ArtGallery.Domains;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace ArtGallery.Migrations
//{
//    [DbContext(typeof(ArtGallleryContext))]
//    [Migration("20241218051925_thirdMigration")]
//    partial class thirdMigration
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.11")
//                .HasAnnotation("Relational:MaxIdentifierLength", 64);

//            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

//            modelBuilder.Entity("ArtGallery.Domains.Comment", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

//                    b.Property<long>("CommentByUser")
//                        .HasColumnType("bigint");

//                    b.Property<string>("CommentText")
//                        .IsRequired()
//                        .HasColumnType("longtext");

//                    b.Property<DateTime>("DateTime")
//                        .HasColumnType("datetime(6)");

//                    b.Property<long>("ProductId")
//                        .HasColumnType("bigint");

//                    b.HasKey("Id");

//                    b.HasIndex("CommentByUser");

//                    b.HasIndex("ProductId");

//                    b.ToTable("Comments");
//                });

//            modelBuilder.Entity("ArtGallery.Domains.Like", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

//                    b.Property<DateTime>("DateTime")
//                        .HasColumnType("datetime(6)");

//                    b.Property<long>("LikedByUser")
//                        .HasColumnType("bigint");

//                    b.Property<long>("ProductId")
//                        .HasColumnType("bigint");

//                    b.HasKey("Id");

//                    b.HasIndex("LikedByUser");

//                    b.HasIndex("ProductId");

//                    b.ToTable("Likes");
//                });

//            modelBuilder.Entity("ArtGallery.Domains.Product", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

//                    b.Property<long>("AddedByUser")
//                        .HasColumnType("bigint");

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasColumnType("longtext");

//                    b.Property<string>("ImageUrl")
//                        .IsRequired()
//                        .HasColumnType("longtext");

//                    b.Property<bool>("IsAvailable")
//                        .HasColumnType("tinyint(1)");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("longtext");

//                    b.Property<double>("Price")
//                        .HasColumnType("double");

//                    b.Property<int>("StatusEnum")
//                        .HasColumnType("int");

//                    b.Property<int>("Stock")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("AddedByUser");

//                    b.ToTable("Products");
//                });

//            modelBuilder.Entity("ArtGallery.Domains.User", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

//                    b.Property<int>("Age")
//                        .HasColumnType("int");

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("longtext");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasColumnType("longtext");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasColumnType("longtext");

//                    b.Property<string>("Password")
//                        .IsRequired()
//                        .HasColumnType("longtext");

//                    b.Property<string>("PhoneNumber")
//                        .IsRequired()
//                        .HasColumnType("longtext");

//                    b.Property<string>("Role")
//                        .IsRequired()
//                        .HasColumnType("longtext");

//                    b.HasKey("Id");

//                    b.ToTable("Users");
//                });

//            modelBuilder.Entity("ArtGallery.Domains.Comment", b =>
//                {
//                    b.HasOne("ArtGallery.Domains.User", "User")
//                        .WithMany()
//                        .HasForeignKey("CommentByUser")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("ArtGallery.Domains.Product", "Product")
//                        .WithMany("Comments")
//                        .HasForeignKey("ProductId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Product");

//                    b.Navigation("User");
//                });

//            modelBuilder.Entity("ArtGallery.Domains.Like", b =>
//                {
//                    b.HasOne("ArtGallery.Domains.User", "User")
//                        .WithMany()
//                        .HasForeignKey("LikedByUser")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("ArtGallery.Domains.Product", "Product")
//                        .WithMany("Likes")
//                        .HasForeignKey("ProductId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Product");

//                    b.Navigation("User");
//                });

//            modelBuilder.Entity("ArtGallery.Domains.Product", b =>
//                {
//                    b.HasOne("ArtGallery.Domains.User", "User")
//                        .WithMany()
//                        .HasForeignKey("AddedByUser")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("User");
//                });

//            modelBuilder.Entity("ArtGallery.Domains.Product", b =>
//                {
//                    b.Navigation("Comments");

//                    b.Navigation("Likes");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
